# Dependabot configuration for AdvanceGG
# Automatically creates PRs for dependency updates

version: 2
updates:
  # Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "GrandpaEJ"
    assignees:
      - "GrandpaEJ"
    commit-message:
      prefix: "🔄"
      include: "scope"
    labels:
      - "dependencies"
      - "go"
      - "automated"

  # Python ecosystem
  - package-ecosystem: "pip"
    directory: "/ecosystem/python"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:30"
    open-pull-requests-limit: 5
    reviewers:
      - "GrandpaEJ"
    assignees:
      - "GrandpaEJ"
    commit-message:
      prefix: "🐍"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
      - "automated"

  # Node.js ecosystem
  - package-ecosystem: "npm"
    directory: "/ecosystem/nodejs"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    open-pull-requests-limit: 5
    reviewers:
      - "GrandpaEJ"
    assignees:
      - "GrandpaEJ"
    commit-message:
      prefix: "🟨"
      include: "scope"
    labels:
      - "dependencies"
      - "nodejs"
      - "automated"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:30"
    open-pull-requests-limit: 3
    reviewers:
      - "GrandpaEJ"
    assignees:
      - "GrandpaEJ"
    commit-message:
      prefix: "🔧"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "automated"
