name: 🚀 Release Request
description: Request a new release of AdvanceGG
title: "[Release] v"
labels: ["release", "enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🚀 Release Request
        
        Use this template to request a new release of AdvanceGG.
        
        **Note:** Only maintainers can trigger releases using the GitHub Actions workflow.

  - type: input
    id: version
    attributes:
      label: Release Version
      description: What version should be released? (e.g., 1.0.0, 1.1.0, 2.0.0-beta.1)
      placeholder: "1.0.0"
    validations:
      required: true

  - type: dropdown
    id: release-type
    attributes:
      label: Release Type
      description: What type of release is this?
      options:
        - patch (bug fixes)
        - minor (new features, backward compatible)
        - major (breaking changes)
        - prerelease (alpha, beta, rc)
    validations:
      required: true

  - type: checkboxes
    id: release-checklist
    attributes:
      label: Pre-release Checklist
      description: Ensure all items are completed before release
      options:
        - label: All tests are passing
          required: true
        - label: Documentation is up to date
          required: true
        - label: CHANGELOG.md has been updated
          required: true
        - label: Version numbers are consistent across all packages
          required: true
        - label: Security scan has been completed
          required: true
        - label: Performance benchmarks are acceptable
          required: true

  - type: textarea
    id: changelog
    attributes:
      label: Changelog
      description: What's new in this release? (This will be included in release notes)
      placeholder: |
        ## New Features
        - Added support for...
        - Improved performance of...
        
        ## Bug Fixes
        - Fixed issue with...
        - Resolved memory leak in...
        
        ## Breaking Changes
        - Changed API for...
        - Removed deprecated...
    validations:
      required: true

  - type: checkboxes
    id: platforms
    attributes:
      label: Target Platforms
      description: Which platforms should be included in this release?
      options:
        - label: Windows (x64)
          required: false
        - label: Windows (ARM64)
          required: false
        - label: macOS (Intel)
          required: false
        - label: macOS (Apple Silicon)
          required: false
        - label: Linux (x64)
          required: false
        - label: Linux (ARM64)
          required: false
        - label: Linux (ARMv7)
          required: false

  - type: checkboxes
    id: packages
    attributes:
      label: Package Distribution
      description: Which package repositories should receive this release?
      options:
        - label: PyPI (Python package)
          required: false
        - label: npm (Node.js package)
          required: false
        - label: GitHub Releases (binaries)
          required: false

  - type: dropdown
    id: urgency
    attributes:
      label: Release Urgency
      description: How urgent is this release?
      options:
        - low (routine release)
        - medium (important features/fixes)
        - high (critical security/bug fixes)
        - critical (emergency release)
    validations:
      required: true

  - type: textarea
    id: testing-notes
    attributes:
      label: Testing Notes
      description: Any specific testing that has been done or should be done?
      placeholder: |
        - Tested on Windows 11, macOS 13, Ubuntu 22.04
        - Verified backward compatibility with v1.x
        - Performance regression tests passed
        - Memory leak tests completed

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information about this release?
      placeholder: |
        - Dependencies updated
        - Security vulnerabilities addressed
        - Community feedback incorporated
